#!/usr/bin/env python3

import argparse
import os
import re
import zipfile

from tempfile import TemporaryDirectory

TMPDIR = TemporaryDirectory()

LOGDIRS = [
    'application-logs',
]


def _arguments():
    parser = argparse.ArgumentParser(
        description='CLI tool to clean atlassian support.zip from various data',
    )
    parser.add_argument(
        'supportzip',
        help='Path to support zip file to be cleaned',
    )
    parser.add_argument(
        'baseurl',
        help='Base-URL of the corresponding system',
    )
    parser.add_argument(
        '--debug', '-d',
        action='store_true',
        help='activate debug log level',
    )
    return parser.parse_args()


def _prepare():
    os.remove('cleaned.zip')


def _extract_zip(supportzip: str):
    supportzip = zipfile.ZipFile(supportzip, 'r')
    supportzip.extractall(TMPDIR.name)
    supportzip.close()


def _clean_logs(baseurl: str):
    for logdir in LOGDIRS:
        _replace_pattern_in_logs(  # Clean URL
            pattern=re.escape(baseurl),
            replacement='URL_CLEANED',
            logdir=logdir
        )
        _replace_pattern_in_logs(  # Clean user names
            pattern='userName: \\S*',
            replacement='userName: USERNAME_CLEANED',
            logdir=logdir
        )


def _replace_pattern_in_logs(pattern: str, replacement: str, logdir: str):
    applogfiles = os.listdir(f'{TMPDIR.name}/{logdir}/')
    for logfile in applogfiles:
        with open(f'{TMPDIR.name}/{logdir}/{logfile}', 'r') as file:
            logcontent = file.read()
            logcontent, nr = re.subn(pattern=re.compile(pattern), repl=replacement, string=logcontent)
            print(f'{nr} replacements ({replacement}) in {logfile}')
        with open(f'{TMPDIR.name}/{logdir}/{logfile}', 'w+') as file:
            file.write(logcontent)


def _create_cleaned_zip():
    with zipfile.ZipFile('cleaned.zip', 'w', zipfile.ZIP_DEFLATED) as cleanedzip:
        _zip_dir(TMPDIR.name, cleanedzip)


def _zip_dir(path: str, ziph: zipfile.ZipFile):
    for root, dirs, files in os.walk(path):
        for file in files:
            filepath = os.path.join(root, file)
            ziph.write(filename=filepath, arcname=filepath[len(path):])


def _cleanup():
    TMPDIR.cleanup()


if __name__ == '__main__':
    args = _arguments()

    print('---')
    print('CLI tool to clean atlassian support.zip from various data')
    print('---')

    try:
        _prepare()
    except:
        pass

    print('Extract support zip')
    _extract_zip(supportzip=args.supportzip)

    print('Clean unwanted information:')
    _clean_logs(baseurl=args.baseurl)

    print('Create cleaned.zip')
    _create_cleaned_zip()

    _cleanup()
